-- Create the products table (if it doesn't exist)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  platform text not null,
  category text,
  name text,
  price numeric,
  mrp numeric,
  weight text,
  eta text,
  availability text,
  image_url text,
  product_url text unique,
  scraped_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Policies (Drop first to avoid errors on re-run)
drop policy if exists "Enable read access for all users" on public.products;
create policy "Enable read access for all users"
on public.products for select
using (true);

drop policy if exists "Enable insert for service role" on public.products;
create policy "Enable insert for service role"
on public.products for insert
with check (true);

drop policy if exists "Enable update for service role" on public.products;
create policy "Enable update for service role"
on public.products for update
using (true);
